server:
  port: 8080


config:
  client:
    origin: http://localhost:3000
  password:
    strength: 10
  firebase:
    service-key: serviceAccountKey.json
  jwt:
    secret: anfoawhfafawkefhbwkjlfeopwehfolawefh
  cookie:
    domain: localhost


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/member?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
