server:
  port: 8080


config:
  client:
    origin: ${DOMAIN_IP}
  password:
    strength: ${ENCRYPTION_STRENGTH}
  firebase:
    service-key: /etc/config/serviceAccountKey.json
  jwt:
    secret: ${JWT_SECRET}
  cookie:
    domain: ${COOKIE_IP}

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL}:${MYSQL_PORT}/member?serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: ${KAFKA_URL}:${KAFKA_PORT}
